name: "StackSpot Workflow"
description: "StackSpot Workflow"
author: "StackSpot"
branding:
  icon: "truck"
  color: "purple"
inputs:
  execution-id:
    description: "Execution ID"
    required: true
  client-id:
    description: "Client ID StackSpot"
    required: true
  client-secret:
    description: "Client Secret StackSpot"
    required: true
  realm:
    description: "Realm StackSpot"
    required: true
  debug:
    description: "Debug Execution"
    required: true
  repository-url:
    description: "Repository URL to commit files"
    required: false
  idm-base-url:
    description: "StackSpot IDM base url"
    required: false
    default: "https://idm.stackspot.com"
  workflow-api-base-url:
    description: "Workflow API base url"
    required: false
    default: "https://workflow-api.v1.stackspot.com"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: bash ./entrypoint.sh ${{ inputs.execution-id }} ${{ inputs.client-id }} ${{ inputs.client-secret }} ${{ inputs.realm }} ${{ inputs.debug }} ${{ inputs.repository-url }} ${{ inputs.idm-base-url }} ${{ inputs.workflow-api-base-url }}