name: Use StackSpot Workflow

on:
  workflow_dispatch:
    inputs:
      execution-id:
        required: true
      repository-url:
        required: false
      debug:
        type: choice
        options:
          - true
          - false

jobs:
  stackspot-workflow:
    environment: 'stg'
    runs-on: ${{ vars.ACTION_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stack Spot Workflow
        uses: ./
        with:
          execution-id: "${{ github.event.inputs.execution-id }}"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          realm: "${{ vars.REALM }}"
          debug: "${{ github.event.inputs.debug }}"
          repository-url: "${{ github.event.inputs.repository-url }}"

      - name: Logs CLI
        if: failure()
        run: sudo cat /home/runner/work/_temp/_github_home/.stk-stg/logs/logs.log

      - name: Debug Http
        if: "${{ inputs.debug == 'true' && always() }}"
        run: sudo cat /home/runner/work/_temp/_github_home/.stk-stg/debug/http.txt