name: Test StackSpot Workflow action

on:
  workflow_dispatch:
    inputs:
      execution-id:
        required: true
      repository-url:
        required: false
      debug:
        type: choice
        options:
          - true
          - false

jobs:
  stackspot-workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stack Spot Workflow
        uses: ./
        with:
          execution-id: "${{ github.event.inputs.execution-id }}"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          realm: "${{ vars.REALM }}"
          debug: "${{ github.event.inputs.debug }}"
          repository-url: "${{ github.event.inputs.repository-url }}"
          origin-branch: develop
          feature-branch: my-custom-feature-branch-${{ env.TIMESTAMP }}
          extra-inputs: '{"teste": "teste"}'
